---
title: "week8_inclass"
output: html_document
date: "2023-10-30"
---

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(naniar)
library(VIM)
library(scales)
library(mice)
d <- read_csv("data/original/finaldata.csv")

```

```{r}
vis_miss(d)
```

```{r}
aggr(d, numbers = TRUE, prop = c(TRUE, FALSE))
```

```{r}
d$GDP <- d$GDP / 1000
d$popdens <- rescale(d$popdens, to=c(0,1))

preds <- as.formula("~ armconf1 + GDP+OECD+popdens+urban+agedep+male_edu+
                    temp+earthquake+drought+ISO+as.factor(year)")
matmormod <- lm(update.formula(preds, matmor~.), data=d)
summary(matmormod)
un5mormod <- lm(update.formula(preds, un5mor~.), data=d)
summary(un5mormod)
infmormod <- lm(update.formula(preds, infmor~.), data=d)
summary(infmormod)
neomormod <- lm(update.formula(preds, neomor~.), data=d)
summary(neomormod)

```

```{r}
set.seed(16)
d$ISO <- as.numeric(as.factor(d$ISO))


mi0 <- mice(d, seed = 1, m = 1, maxit = 0, print = F)
# mice(d, seed = 1, m = 10, maxit = 20, method = meth, print = F)
meth <- mi0$method
meth

meth["GDP"] <- "2l.pan"
meth["popdens"] <- "2l.pan"
meth["urban"] <- "2l.pan"
meth["male_edu"] <- "2l.pan"
meth["temp"] <- "2l.pan"
meth["matmor"] <- "2l.pan"
meth["infmor"] <- "2l.pan"
meth["neomor"] <- "2l.pan"
meth["un5mor"] <- "2l.pan"

# mice.multi.out1 <- mice(d, seed = 1, m = 10, maxit = 20, method = meth, print = F)
# mice.multi.out1$meth

pred <- mice.multi.out1$predictorMatrix
pred

pred[c("GDP", "popdens", "urban", "male_edu", "temp", "matmor", "infmor", "neomor", "un5mor"), "ISO"] <- -2
mice.multi.out  <- mice(d, seed = 100, m = 10, maxit = 20,
                  method = meth,
                  predictorMatrix = pred, print = F)
save(mice.multi.out, file = "miceout.Rda")

```

```{r}
fit.multi2 <- with(mice.multi.out, 
                   
                   model1 <- lm(matmor~ armconf1 + GDP+OECD+popdens+urban+agedep+male_edu+
                    temp+earthquake+drought+ISO+as.factor(year)))

summary(pool(fit.multi2))

fit.multi3 <- with(mice.multi.out, 
                   
                   model1 <- lm(infmor~ armconf1 + GDP+OECD+popdens+urban+agedep+male_edu+
                    temp+earthquake+drought+ISO+as.factor(year)))

summary(pool(fit.multi3))

fit.multi4 <- with(mice.multi.out, 
                   
                   model1 <- lm(neomor~ armconf1 + GDP+OECD+popdens+urban+agedep+male_edu+
                    temp+earthquake+drought+ISO+as.factor(year)))

summary(pool(fit.multi4))

fit.multi5 <- with(mice.multi.out, 
                   
                   model1 <- lm(un5mor~ armconf1 + GDP+OECD+popdens+urban+agedep+male_edu+
                    temp+earthquake+drought+ISO+as.factor(year)))

summary(pool(fit.multi5))

```

